---
replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: linuxserver/radarr
  tag: nightly
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

paths:
  downloads: /d/downloads/radaar
  config: /f/volumes/radarr/config
  movies: /f/volumes/radarr/movies
  watchdirs: /f/volumes/radarr/watchdirs

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  paths: ["/"]
  hosts:
    - radarr.localhost
  tls:
    - hosts:
      - radarr.localhost

resources:
  limits:
   memory: 1Gi
  requests:
   memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
