---
replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: linuxserver/deluge
  tag: lastest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

paths:
  downloads: /d/downloads/deluge
  config: /f/volumes/deluge/config

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  paths: ["/"]
  hosts:
    - deluge.localhost
  tls:
    - hosts:
      - deluge.localhost

resources:
  limits:
   memory: 1Gi
  requests:
   memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
