---
replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: linuxserver/nzbget
  tag: amd64-latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

paths:
  downloads: /d/downloads/nzbget
  config: /f/volumes/nzbget/config

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  paths: ["/"]
  hosts:
    - nzbget.localhost
  tls:
    - hosts:
      - nzbget.localhost

basicAuth: "bnpiZ2V0OnRlZ2J6bjY3ODk="

resources:
  limits:
   memory: 1Gi
  requests:
   memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
